### ISSUE TITLE
Handle camps

### ISSUE THREAD

**Issue by JacobJax** [Room04/YelpCamp-Backend#4]
## Tasks
- [x] Create new camp
- [x] Get all camps
- [x] Get single camp
- [ ] Update single camp
- [ ] Search for camps
